try :
    num = int(input("Enter your Number: "))
    print(num)
    
    
except ValueError as ex:
    print("Exception: ", ex)
    
    
print("√èam Outside the Try Block.") 
